version: '3'

# define the network
networks:
  web-network:

# containers...
services:
  # cli container (phpUnit)
  php-cli:
    build:
      context: .docker/php-cli
    tty: true
    volumes:
      - ../:/var/www
    networks:
      - web-network

  # fpm container
  php-fast-cgi:
    build:
      context: .docker/php-fpm
    tty: true
    volumes:
      - ../:/var/www
    networks:
      - web-network

  # nginx web server (could be used as a proxy)
  webserver:
    build:
      context: .docker/nginx
    ports:
      - "80:80"
    tty: true
    # connect to code and nginx config
    volumes:
      - ../:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  # mysql database
  database:
    build:
      context: .docker/mysql
    volumes:
      - ../dbFiles:/dbFiles/
      - ../dbScripts:/docker-entrypoint-initdb.d/
    networks:
      - web-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=examplePassword
      - MYSQL_DATABASE=ringingV2
      - MYSQL_USER=ringer
      - MYSQL_PASSWORD=examplePassword2