-- deanery
INSERT INTO deanery
VALUES (1, 'Aylesbeare', 'south');
INSERT INTO deanery
VALUES (2, 'Barnstaple', 'north');
INSERT INTO deanery
VALUES (3, 'Cadbury', 'north');
INSERT INTO deanery
VALUES (4, 'Christianity', 'south');
INSERT INTO deanery
VALUES (5, 'Cullompton', 'north');
INSERT INTO deanery
VALUES (6, 'Hartland', 'north');
INSERT INTO deanery
VALUES (7, 'Holsworthy', 'north');
INSERT INTO deanery
VALUES (8, 'Honiton', 'south');
INSERT INTO deanery
VALUES (9, 'Ivybridge', 'south');
INSERT INTO deanery
VALUES (10, 'Kenn', 'south');
INSERT INTO deanery
VALUES (11, 'Moreton', 'south');
INSERT INTO deanery
VALUES (12, 'Newton Abbot and Ipplepen', 'south');
INSERT INTO deanery
VALUES (13, 'None', 'n/a');
INSERT INTO deanery
VALUES (14, 'Not Applicable', 'n/a');
INSERT INTO deanery
VALUES (15, 'Okehampton', 'north');
INSERT INTO deanery
VALUES (16, 'Ottery', 'south');
INSERT INTO deanery
VALUES (17, 'Out of County', 'outOfCounty');
INSERT INTO deanery
VALUES (18, 'Plymouth (Devonport, Moorside, Sutton)', 'south');
INSERT INTO deanery
VALUES (19, 'Shirwell', 'north');
INSERT INTO deanery
VALUES (20, 'South Molton', 'north');
INSERT INTO deanery
VALUES (21, 'Tavistock', 'south');
INSERT INTO deanery
VALUES (22, 'Tiverton', 'north');
INSERT INTO deanery
VALUES (23, 'Torbay', 'south');
INSERT INTO deanery
VALUES (24, 'Torrington', 'north');
INSERT INTO deanery
VALUES (25, 'Totnes', 'south');
INSERT INTO deanery
VALUES (26, 'Woodleigh', 'south');

-- ringer
INSERT INTO ringer
VALUES (1, 'Fred', 'Axworthy', NULL);
INSERT INTO ringer
VALUES (2, 'Philip', 'Stoneman', NULL);
INSERT INTO ringer
VALUES (3, 'William', 'Ford', NULL);
INSERT INTO ringer
VALUES (4, 'James', 'Pope', NULL);
INSERT INTO ringer
VALUES (5, 'Frederick', 'Pope', NULL);
INSERT INTO ringer
VALUES (6, 'William Oliver', 'Priest', NULL);
INSERT INTO ringer
VALUES (7, 'Wallace', 'Mortimore', NULL);
INSERT INTO ringer
VALUES (8, 'Alfred', 'Lias', NULL);
INSERT INTO ringer VALUES (9, 'Walter', 'Martin', NULL);
INSERT INTO ringer VALUES (10, 'Robert James', 'Bennett', NULL);
INSERT INTO ringer VALUES (11, 'Hilary', 'Trout', NULL);
INSERT INTO ringer VALUES (12, 'Susan', 'Ashton', 'Was Kerslake');
INSERT INTO ringer VALUES (13, 'Martin', 'Crew', NULL);
INSERT INTO ringer VALUES (14, 'Stephen', 'Trout', NULL);
INSERT INTO ringer VALUES (15, 'David', 'Trout', NULL);
INSERT INTO ringer VALUES (16, 'Roger', 'Trout', NULL);
INSERT INTO ringer VALUES (17, 'Ryan', 'Trout', NULL);
INSERT INTO ringer VALUES (18, 'Robert', 'Hackworthy', 'Known as Bob');
INSERT INTO ringer VALUES (19, 'Peter', 'Brewer', NULL);
INSERT INTO ringer VALUES (20, 'Bill', 'Avery', NULL);
INSERT INTO ringer VALUES (21, 'Ian', 'Avery', NULL);
INSERT INTO ringer VALUES (22, 'Jack', 'Hine', NULL);
INSERT INTO ringer VALUES (23, 'Bill', 'Brimecombe', NULL);
INSERT INTO ringer VALUES (24, 'Harry', 'Bowden', NULL);
INSERT INTO ringer VALUES (25, 'Bob', 'Sampson', NULL);
INSERT INTO ringer VALUES (26, 'Sam', 'Slade', NULL);
INSERT INTO ringer VALUES (27, 'Kitch', 'Avery', NULL);
INSERT INTO ringer VALUES (28, 'Peter', 'Wheeler', NULL);
INSERT INTO ringer VALUES (29, 'Sandra', 'Coombes', NULL);
INSERT INTO ringer VALUES (30, 'Mary', 'Mears', NULL);
INSERT INTO ringer VALUES (31, 'Mike', 'Mears', NULL);
INSERT INTO ringer VALUES (32, 'Graham', 'Sharland', NULL);
INSERT INTO ringer VALUES (33, 'Colin', 'Avery', NULL);
INSERT INTO ringer VALUES (34, 'Phil', 'Stevens', NULL);
INSERT INTO ringer VALUES (35, 'Harry', 'Kennar', NULL);
INSERT INTO ringer VALUES (36, 'Simon', 'Ford', NULL);
INSERT INTO ringer VALUES (37, 'John', 'Westlake', NULL);
INSERT INTO ringer VALUES (38, 'Martin', 'Sharland', NULL);
INSERT INTO ringer VALUES (39, 'Lee', 'Avery', NULL);
INSERT INTO ringer VALUES (40, 'James', 'Grant', NULL);
INSERT INTO ringer VALUES (41, 'Elaine', 'Grant', NULL);
INSERT INTO ringer VALUES (42, 'Tim', 'Bayton', NULL);
INSERT INTO ringer VALUES (43, 'Tom', 'Grant', NULL);
INSERT INTO ringer VALUES (44, 'Angela', 'Trout', 'Was Delbridge');
INSERT INTO ringer VALUES (45, 'Suzanne', 'Driscoll', NULL);
INSERT INTO ringer VALUES (46, 'Louise', 'Hornabrook', NULL);
INSERT INTO ringer VALUES (47, 'Emma', 'McCulloch', NULL);
INSERT INTO ringer VALUES (48, 'Alan', 'Brown', NULL);
INSERT INTO ringer VALUES (49, 'Jereme', 'Darke', NULL);
INSERT INTO ringer VALUES (50, 'Derek', 'Jones', NULL);
INSERT INTO ringer VALUES (51, 'Christine', 'Ley', NULL);
INSERT INTO ringer VALUES (52, 'Paul', 'Wright', NULL);
INSERT INTO ringer VALUES (53, 'Gerald', 'Herniman', NULL);
INSERT INTO ringer VALUES (54, 'Steven', 'Facey', NULL);
INSERT INTO ringer VALUES (55, 'Stephen', 'Herniman', NULL);
INSERT INTO ringer VALUES (56, 'Linda', 'Steer', NULL);
INSERT INTO ringer VALUES (57, 'Gary', 'Quicke', NULL);
INSERT INTO ringer VALUES (58, 'James', 'Steer', NULL);
INSERT INTO ringer VALUES (59, 'Denis', 'Cann', NULL);
INSERT INTO ringer VALUES (60, 'Bob', 'Robinson', NULL);
INSERT INTO ringer VALUES (61, 'Hugh', 'Taylor', NULL);
INSERT INTO ringer VALUES (62, 'Graham', 'Pascoe', NULL);
INSERT INTO ringer VALUES (63, 'Paul', 'Pascoe', NULL);
INSERT INTO ringer VALUES (64, 'Herbert', 'Pascoe', 'Known as Pickles');
INSERT INTO ringer VALUES (65, 'Les', 'Hamlyn', NULL);
INSERT INTO ringer VALUES (66, 'Bill', 'Campion', NULL);
INSERT INTO ringer VALUES (67, 'Spencer', 'Keys', NULL);
INSERT INTO ringer VALUES (68, 'Douglas', 'Cock', NULL);
INSERT INTO ringer VALUES (69, 'Bernard', 'Miners', NULL);
INSERT INTO ringer VALUES (70, 'Pat', 'Johnstone', NULL);
INSERT INTO ringer VALUES (71, 'Janet', 'Dietz', 'Was Scaddon');
INSERT INTO ringer VALUES (72, 'Julia', 'Endicott', NULL);
INSERT INTO ringer VALUES (73, 'George', 'Whiddon', NULL);
INSERT INTO ringer VALUES (74, 'John', 'Dietz', NULL);
INSERT INTO ringer VALUES (75, 'Brian', 'Redstone', NULL);
INSERT INTO ringer VALUES (76, 'John', 'Caunter', NULL);
INSERT INTO ringer VALUES (77, 'Stuart', 'Aplin', NULL);
INSERT INTO ringer VALUES (78, 'Colin', 'Symonds', NULL);
INSERT INTO ringer VALUES (79, 'D', 'Northway', NULL);
INSERT INTO ringer VALUES (80, 'Gillian', 'Glover', NULL);
INSERT INTO ringer VALUES (81, 'Graham', 'Hubber', NULL);
INSERT INTO ringer VALUES (82, 'Nicholas', 'Trout', NULL);
INSERT INTO ringer VALUES (83, 'Arthur', 'Doughty', NULL);
INSERT INTO ringer VALUES (84, 'John', 'Devonish', NULL);
INSERT INTO ringer VALUES (85, 'Chris', 'Pascoe', NULL);
INSERT INTO ringer VALUES (86, 'Chris', 'Lock', NULL);
INSERT INTO ringer VALUES (87, 'Colin', 'Adams', NULL);
INSERT INTO ringer VALUES (88, 'Scott', 'Adams', NULL);
INSERT INTO ringer VALUES (89, 'Ryan', 'Brodie', NULL);
INSERT INTO ringer VALUES (90, 'Stephanie', 'Brown', NULL);
INSERT INTO ringer VALUES (91, 'Mervyn', 'Langdon', NULL);
INSERT INTO ringer VALUES (92, 'David', 'Trist', NULL);
INSERT INTO ringer VALUES (93, 'Sam', 'Massey', NULL);
INSERT INTO ringer VALUES (94, 'Julia', 'Jarvis', NULL);
INSERT INTO ringer VALUES (95, 'Colin', 'Heath', NULL);
INSERT INTO ringer VALUES (96, 'Chris', 'Massey', NULL);
INSERT INTO ringer VALUES (97, 'John', 'Kelly', 'BEM');
INSERT INTO ringer VALUES (98, 'Mike', 'Webster', NULL);
INSERT INTO ringer VALUES (99, 'J', 'Snow', NULL);
INSERT INTO ringer VALUES (100, 'M', 'Waldren', NULL);
INSERT INTO ringer VALUES (101, 'H', 'Spear', NULL);
INSERT INTO ringer VALUES (102, 'Ivan', 'Harris', NULL);
INSERT INTO ringer VALUES (103, 'S', 'Rendle', NULL);
INSERT INTO ringer VALUES (104, 'S', 'Knowles', NULL);
INSERT INTO ringer VALUES (105, 'A', 'Mayne', NULL);
INSERT INTO ringer VALUES (106, 'W', 'Lake', NULL);
INSERT INTO ringer VALUES (107, 'Monty', 'Bertram', NULL);
INSERT INTO ringer VALUES (108, 'Colin', 'Tovey', NULL);
INSERT INTO ringer VALUES (109, 'Chris', 'Lethbridge', NULL);
INSERT INTO ringer VALUES (110, 'Steve', 'Ford', NULL);
INSERT INTO ringer VALUES (111, 'John', 'Wheaton', NULL);
INSERT INTO ringer VALUES (112, 'Gerald', 'Arscott', NULL);
INSERT INTO ringer VALUES (113, 'Ivor', 'Warren', NULL);
INSERT INTO ringer VALUES (114, 'Aubrey', 'Headon', NULL);
INSERT INTO ringer VALUES (115, 'W', 'Weeks', NULL);
INSERT INTO ringer VALUES (116, 'Ivor', 'Treeby', NULL);
INSERT INTO ringer VALUES (117, 'Frank', 'Crowe', NULL);
INSERT INTO ringer VALUES (118, 'Ray', 'Treeby', NULL);
INSERT INTO ringer VALUES (119, 'L', 'Collingwood', NULL);
INSERT INTO ringer VALUES (120, 'Jack', 'Rhymes', NULL);
INSERT INTO ringer VALUES (121, 'Christine', 'Pascoe', 'Was Heath');
INSERT INTO ringer VALUES (122, 'Neil', 'Holloway', NULL);
INSERT INTO ringer VALUES (123, 'Mark', 'Lovell', NULL);
INSERT INTO ringer VALUES (124, 'Brett', 'Baldwin', NULL);
INSERT INTO ringer VALUES (125, 'Lesley', 'Rowe', NULL);
INSERT INTO ringer VALUES (126, 'Lauren', 'Rideout', NULL);
INSERT INTO ringer VALUES (127, 'Chris', 'Parker', NULL);
INSERT INTO ringer VALUES (128, 'Sheila', 'Beare', NULL);
INSERT INTO ringer VALUES (129, 'Maggie', 'Sercombe', NULL);
INSERT INTO ringer VALUES (130, 'Marion', 'Ryder', NULL);
INSERT INTO ringer VALUES (131, 'Bev', 'Hinckley', NULL);
INSERT INTO ringer VALUES (132, 'Caroline', 'Keen', NULL);
INSERT INTO ringer VALUES (133, 'Norman', 'Mortimore', NULL);
INSERT INTO ringer VALUES (134, 'John', 'Buckpitt', NULL);
INSERT INTO ringer VALUES (135, 'Frank', 'Allen', NULL);
INSERT INTO ringer VALUES (136, 'Rachel', 'Avery', NULL);
INSERT INTO ringer VALUES (137, 'Maurice', 'Sharland', NULL);
INSERT INTO ringer VALUES (138, 'Daphne', 'Sharland', NULL);
INSERT INTO ringer VALUES (139, 'Ivor', 'Pincombe', NULL);
INSERT INTO ringer VALUES (140, 'Ray', 'Mugridge', NULL);
INSERT INTO ringer VALUES (141, 'Charlie', 'Hard', NULL);
INSERT INTO ringer VALUES (142, 'Kathryn', 'Kerslake', NULL);
INSERT INTO ringer VALUES (143, 'James', 'Kerslake', NULL);
INSERT INTO ringer VALUES (144, 'Steven', 'Came', NULL);
INSERT INTO ringer VALUES (145, 'Michael', 'Adams', NULL);
INSERT INTO ringer VALUES (146, 'Fred', 'Delve', NULL);
INSERT INTO ringer VALUES (147, 'Bill', 'Lamacraft', NULL);
INSERT INTO ringer VALUES (148, 'Wally', 'Snell', NULL);
INSERT INTO ringer VALUES (149, 'Alfie', 'Rice', NULL);
INSERT INTO ringer VALUES (150, 'Gilbert', 'Goff', NULL);
INSERT INTO ringer VALUES (151, 'George', 'Stevens', 'Ide ringer');
INSERT INTO ringer VALUES (152, 'Mervyn', 'Phillips', NULL);
INSERT INTO ringer VALUES (153, 'F', 'White', 'junior');
INSERT INTO ringer VALUES (154, 'G', 'Stevens', NULL);
INSERT INTO ringer VALUES (155, 'L', 'Phillips', NULL);
INSERT INTO ringer VALUES (156, 'Ivor', 'Hookway', NULL);
INSERT INTO ringer VALUES (157, 'L', 'Smale', NULL);
INSERT INTO ringer VALUES (158, 'RB', 'Phillips', NULL);
INSERT INTO ringer VALUES (159, 'D', 'Smale', NULL);
INSERT INTO ringer VALUES (160, 'W', 'White', NULL);
INSERT INTO ringer VALUES (161, 'C', 'Ridge', NULL);

-- judges
INSERT INTO judge VALUES (1, 'Cliff', 'Wilson', NULL);
INSERT INTO judge VALUES (2, 'Colin', 'Avery', 33);
INSERT INTO judge VALUES (3, 'David', 'Trist', 92);
INSERT INTO judge VALUES (4, 'Gill', 'Herniman', NULL);
INSERT INTO judge VALUES (5, 'Graham', 'Sharland', 32);
INSERT INTO judge VALUES (6, 'Helen', 'Robinson', NULL);
INSERT INTO judge VALUES (7, 'James', 'Kerslake', 143);
INSERT INTO judge VALUES (8, 'John', 'Dietz', 74);
INSERT INTO judge VALUES (9, 'John', 'Wickett', NULL);
INSERT INTO judge VALUES (10, 'Maurice', 'Sharland', 137);
INSERT INTO judge VALUES (11, 'Mervyn', 'Langdon', 91);
INSERT INTO judge VALUES (12, 'Mervyn', 'Way', NULL);
INSERT INTO judge VALUES (13, 'Michael', 'Poole', NULL);
INSERT INTO judge VALUES (14, 'Norman', 'Mortimore', 133);
INSERT INTO judge VALUES (15, 'Percy', 'Pester', NULL);
INSERT INTO judge VALUES (16, 'Ray', 'Mugridge', NULL);
INSERT INTO judge VALUES (17, 'Raymond', 'Clements', NULL);
INSERT INTO judge VALUES (18, 'Scott', 'Adams', 88);
INSERT INTO judge VALUES (19, 'Graham', 'Pascoe', 62);
INSERT INTO judge VALUES (20, 'Brian', 'Drake', NULL);
INSERT INTO judge VALUES (21, 'Alan', 'Brown', 48);

-- locations
INSERT INTO location VALUES (1, 'Abbotskerswell', 12, 'The Blessed Virgin Mary', '10cwt');
INSERT INTO location VALUES (2, 'Alwington', 6, 'St Andrew', '11-2-0');
INSERT INTO location VALUES (3, 'Appledore', 6, 'St Mary', '10-3-26');
INSERT INTO location VALUES (4, 'Arlington', 19, 'St James', '11cwt');
INSERT INTO location VALUES (5, 'Ashburton', 25, 'St Andrew', '21-1-6');
INSERT INTO location VALUES (6, 'Ashreigney', 24, 'St James', '9-0-18');
INSERT INTO location VALUES (7, 'Ashwater', 7, 'St Peter ad Vincula', '8-3-1');
INSERT INTO location VALUES (8, 'Atherington', 24, 'St Mary', '11-0-9');
INSERT INTO location VALUES (9, 'Bampton', 22, 'St Michael and All Angels', '14-0-3');
INSERT INTO location VALUES (10, 'Barnstaple', 2, 'St Peter and Mary Magdalene', '19-1-0');
INSERT INTO location VALUES (11, 'Beaford', 24, 'All Saints', '12cwt');
INSERT INTO location VALUES (12, 'Belstone', 15, 'St Mary', '5-2-25');
INSERT INTO location VALUES (13, 'Bere Ferrers', 21, 'St Andrew', '7-3-24');
INSERT INTO location VALUES (14, 'Berry Pomeroy', 25, 'St Mary', '17cwt');
INSERT INTO location VALUES (15, 'Bickington', 11, 'St Mary the Virgin', '7-1-24');
INSERT INTO location VALUES (16, 'Bickleigh (nr Plymouth)', 9, 'St Mary the Virgin', '9-3-27');
INSERT INTO location VALUES (17, 'Bickleigh (nr Tiverton)', 22, 'St Mary', '9-1-14');
INSERT INTO location VALUES (18, 'Bideford', 6, 'St Mary', '17-1-10');
INSERT INTO location VALUES (19, 'Bigbury', 26, 'St Lawrence', '7-2-27');
INSERT INTO location VALUES (20, 'Bishops Nympton', 20, 'St Mary the Virgin', '10-1-10');
INSERT INTO location VALUES (21, 'Bishops Tawton', 2, 'St John the Baptist', '9-2-20');
INSERT INTO location VALUES (22, 'Bishopsteignton', 10, 'St John the Baptist', '10-1-24');
INSERT INTO location VALUES (23, 'Black Torrington', 7, 'St Mary', '8-3-9');
INSERT INTO location VALUES (24, 'Blackawton', 26, 'St Michael', '11-3-1');
INSERT INTO location VALUES (25, 'Bovey Tracey', 11, 'SS Peter, Paul and Thomas', '14-2-26');
INSERT INTO location VALUES (26, 'Bow', 3, 'St Bartholomew', '13-2-23');
INSERT INTO location VALUES (27, 'Bradford', 7, 'All Saints', '10-2-8');
INSERT INTO location VALUES (28, 'Bradworthy', 7, 'St John the Baptist', '9-3-8');
INSERT INTO location VALUES (29, 'Branscombe', 8, 'St Winifred', '14cwt');
INSERT INTO location VALUES (30, 'Bratton Clovelly', 15, 'St Mary the Virgin', '12cwt');
INSERT INTO location VALUES (31, 'Bratton Fleming', 19, 'St Peter', '14-2-0');
INSERT INTO location VALUES (32, 'Braunton', 2, 'St Brannock', '16-0-25');
INSERT INTO location VALUES (33, 'Bridestowe', 15, 'St Bridget', '13-0-5');
INSERT INTO location VALUES (34, 'Bridford', 10, 'St Thomas a Becket', '9cwt');
INSERT INTO location VALUES (35, 'Bridgerule', 7, 'St Bridget', '10-1-21');
INSERT INTO location VALUES (36, 'Brixham', 23, 'The Blessed Virgin Mary', '17-0-4');
INSERT INTO location VALUES (37, 'Brixton', 9, 'St Mary', '13cwt');
INSERT INTO location VALUES (38, 'Broadhempston', 25, 'SS Peter and Paul', '12cwt');
INSERT INTO location VALUES (39, 'Broadwoodkelly', 24, 'All Saints', '9-3-14');
INSERT INTO location VALUES (40, 'Buckerell', 16, 'SS Mary and Giles', '8-1-4');
INSERT INTO location VALUES (41, 'Buckfastleigh', 25, 'Holy Trinity', '15-2-21');
INSERT INTO location VALUES (42, 'Buckland Brewer', 6, 'SS Mary and Benedict', '12-3-17');
INSERT INTO location VALUES (43, 'Buckland in the Moor', 11, 'St Peter', '7-0-17');
INSERT INTO location VALUES (44, 'Buckland Monachorum', 21, 'St Andrew', '15-3-5');
INSERT INTO location VALUES (45, 'Burrington', 20, 'Holy Trinity', '11-2-11');
INSERT INTO location VALUES (46, 'Chagford', 15, 'St Michael', '18-0-2');
INSERT INTO location VALUES (47, 'Chardstock', 8, 'St Andrew', '12-1-27');
INSERT INTO location VALUES (48, 'Charleton', 26, 'St Mary', '9-2-13');
INSERT INTO location VALUES (49, 'Chawleigh', 20, 'St James', '15-3-23');
INSERT INTO location VALUES (50, 'Cheriton Bishop', 10, 'St Mary', '14cwt');
INSERT INTO location VALUES (51, 'Cheriton Fitzpaine', 3, 'St Matthew', '13-1-10');
INSERT INTO location VALUES (52, 'Chittlehampton', 20, 'St Hieritha', '13-0-15');
INSERT INTO location VALUES (53, 'Chivelstone', 26, 'St Sylvester', '12cwt');
INSERT INTO location VALUES (54, 'Christow', 10, 'St James', '11-2-20');
INSERT INTO location VALUES (55, 'Chudleigh', 11, 'SS Mary and Martin', '12-2-23');
INSERT INTO location VALUES (56, 'Chulmleigh', 20, 'St Mary Magdalene', '22-0-26');
INSERT INTO location VALUES (57, 'Churchstow', 26, 'St Mary', '16cwt');
INSERT INTO location VALUES (58, 'Churston Ferrers', 23, 'St Mary the Virgin', '12-0-15');
INSERT INTO location VALUES (59, 'Clawton', 7, 'St Leonard', '8-1-25');
INSERT INTO location VALUES (60, 'Clovelly', 6, 'All Saints', '10-1-21');
INSERT INTO location VALUES (61, 'Clyst St George', 1, 'St George', '10-2-21');
INSERT INTO location VALUES (62, 'Coffinswell', 12, 'St Bartholomew', '11-0-5');
INSERT INTO location VALUES (63, 'Colaton Raleigh', 16, 'St John the Baptist', '12cwt');
INSERT INTO location VALUES (64, 'Coldridge', 3, 'St Matthew', '13cwt');
INSERT INTO location VALUES (65, 'Colebrooke', 3, 'St Andrew', '17-3-21');
INSERT INTO location VALUES (66, 'Collaton St Mary', 25, 'St Mary', '7-1-25');
INSERT INTO location VALUES (67, 'Combe Martin', 19, 'St Peter ad Vincula', '10-0-21');
INSERT INTO location VALUES (68, 'Combe Raleigh', 8, 'St Nicholas', '5-2-19');
INSERT INTO location VALUES (69, 'Combeinteignhead', 12, 'All Saints', '10cwt');
INSERT INTO location VALUES (70, 'Cornwood', 9, 'St Michael and All Angels', '9-3-12');
INSERT INTO location VALUES (71, 'Cornworthy', 25, 'St Peter', '9-3-6');
INSERT INTO location VALUES (72, 'Cullompton', 5, 'St Andrew', '19-2-4');
INSERT INTO location VALUES (73, 'Dartington', 25, 'St Mary', '17cwt');
INSERT INTO location VALUES (74, 'Dartmouth, St Petrox', 25, 'St Petrox', '7-3-9');
INSERT INTO location VALUES (75, 'Dartmouth, St Saviour', 25, 'St Saviour', '18-2-14');
INSERT INTO location VALUES (76, 'Dartmouth, Townstal', 25, 'St Clement', '7-2-11');
INSERT INTO location VALUES (77, 'Dawlish', 10, 'St Gregory', '11-2-21');
INSERT INTO location VALUES (78, 'Dean Prior', 25, 'St George the Martyr', '11-2-24');
INSERT INTO location VALUES (79, 'Diptford', 25, 'St Mary the Virgin', '11-3-12');
INSERT INTO location VALUES (80, 'Dittisham', 25, 'St George', '12-1-8');
INSERT INTO location VALUES (81, 'Dodbrooke', 26, 'St Thomas a Becket', '7-0-10');
INSERT INTO location VALUES (82, 'Doddiscombsleigh', 10, 'St Michael', '10-2-14');
INSERT INTO location VALUES (83, 'Dolton', 24, 'St Edmund King and Martyr', '13-1-21');
INSERT INTO location VALUES (84, 'Dowland', 24, 'St Peter', '4-3-0');
INSERT INTO location VALUES (85, 'Down St Mary', 3, 'St Mary the Virgin', '7-3-16');
INSERT INTO location VALUES (86, 'Drewsteignton', 15, 'Holy Trinity', '13-3-7');
INSERT INTO location VALUES (87, 'Dunsford', 10, 'St Mary', '12-3-16');
INSERT INTO location VALUES (88, 'East Allington', 26, 'St Andrew', '14cwt');
INSERT INTO location VALUES (89, 'East Budleigh', 1, 'All Saints', '9-0-0');
INSERT INTO location VALUES (90, 'East Portlemouth', 26, 'St Winwaloe Onocaus', '13-3-22');
INSERT INTO location VALUES (91, 'East Teignmouth (St Michael)', 10, 'St Michael', '22-1-0');
INSERT INTO location VALUES (92, 'East Worlington', 20, 'St Mary', '5-1-23');
INSERT INTO location VALUES (93, 'Ermington', 9, 'SS Peter and Paul', '14-1-13');
INSERT INTO location VALUES (94, 'Exbourne', 15, 'St Mary the Virgin', '8-2-14');
INSERT INTO location VALUES (95, 'Exeter Cathedral', 4, 'St Peter', '72-2-2');
INSERT INTO location VALUES (96, 'Exeter, Alphington', 10, 'St Michael and All Angels', '13-1-12');
INSERT INTO location VALUES (97, 'Exeter, Pinhoe', 1, 'St Michael and All Angels', '10-0-19');
INSERT INTO location VALUES (98, 'Exeter, St David', 4, 'St David', '11-2-23');
INSERT INTO location VALUES (99, 'Exeter, St Mark', 4, 'St Mark', '12-1-19');
INSERT INTO location VALUES (100, 'Exeter, St Petrock', 4, 'St Petrock', '5cwt');
INSERT INTO location VALUES (101, 'Exminster', 10, 'St Martin of Tours', '17-3-25');
INSERT INTO location VALUES (102, 'Exmouth, Littleham', 1, 'St Margaret', '7-2-11');
INSERT INTO location VALUES (103, 'Feniton', 16, 'St Andrew', '9cwt');
INSERT INTO location VALUES (104, 'Filleigh', 20, 'St Paul', '6-0-12');
INSERT INTO location VALUES (105, 'Fremington', 2, 'St Peter', '8-3-19');
INSERT INTO location VALUES (106, 'Frithelstock', 24, 'SS Mary and Gregory', '17cwt');
INSERT INTO location VALUES (107, 'Georgeham', 2, 'St George', '12-0-22');
INSERT INTO location VALUES (108, 'Goodleigh', 2, 'St Gregory', '7-1-18');
INSERT INTO location VALUES (109, 'Great Torrington', 24, 'St Michael', '14-3-4');
INSERT INTO location VALUES (110, 'Halberton', 5, 'St Andrew', '17-2-6');
INSERT INTO location VALUES (111, 'Halwell', 25, 'St Leonard', '12cwt');
INSERT INTO location VALUES (112, 'Harberton', 25, 'St Andrew', '16cwt');
INSERT INTO location VALUES (113, 'Hartland', 6, 'St Nectan', '17-2-8');
INSERT INTO location VALUES (114, 'Hatherleigh', 15, 'St John the Baptist', '13-2-6');
INSERT INTO location VALUES (115, 'Heanton Punchardon', 2, 'St Augustine', '10-2-24');
INSERT INTO location VALUES (116, 'High Bickington', 24, 'St Mary', '9-1-25');
INSERT INTO location VALUES (117, 'Highweek', 12, 'All Saints', '11-1-11');
INSERT INTO location VALUES (118, 'Holbeton', 9, 'All Saints', '13-3-14');
INSERT INTO location VALUES (119, 'Holcombe Burnell', 10, 'St John the Baptist', '11-0-27');
INSERT INTO location VALUES (120, 'Holne', 11, 'St Mary the Virgin', '8-2-24');
INSERT INTO location VALUES (121, 'Holsworthy', 7, 'SS Peter and Paul', '15-0-0');
INSERT INTO location VALUES (122, 'Huish Episcopi', 17, 'The Blessed Virgin Mary', '15-2-7');
INSERT INTO location VALUES (123, 'Huntsham', 22, 'All Saints', '8-0-27');
INSERT INTO location VALUES (124, 'Iddesleigh', 24, 'St James', '9-1-21');
INSERT INTO location VALUES (125, 'Ide', 10, 'St Ida', '7-0-18');
INSERT INTO location VALUES (126, 'Ideford', 10, 'St Mary the Virgin', '7-3-9');
INSERT INTO location VALUES (127, 'Ilfracombe, Holy Trinity', 2, 'Holy Trinity', '12-0-20');
INSERT INTO location VALUES (128, 'Ilfracombe, Ss Philip and James', 2, 'Ss Philip and James', '11-0-26');
INSERT INTO location VALUES (129, 'Ilsington', 11, 'St Michael', '10-3-13');
INSERT INTO location VALUES (130, 'Inwardleigh', 15, 'St Petroc', '6-3-4');
INSERT INTO location VALUES (131, 'Ipplepen', 12, 'St Andrew', '18-1-0');
INSERT INTO location VALUES (132, 'Jacobstowe', 15, 'St James', '6-2-2');
INSERT INTO location VALUES (133, 'Kenn', 10, 'St Andrew', '13-1-25');
INSERT INTO location VALUES (134, 'Kentisbeare', 5, 'St Mary', '10-1-2');
INSERT INTO location VALUES (135, 'Kentisbury', 19, 'St Thomas', '8cwt');
INSERT INTO location VALUES (136, 'Kenton', 10, 'All Saints', '12-1-19');
INSERT INTO location VALUES (137, 'Kilkhampton', 17, 'St James the Greater', '11-3-23');
INSERT INTO location VALUES (138, 'Kilmington', 8, 'St Giles', '10-1-4');
INSERT INTO location VALUES (139, 'Kings Nympton', 20, 'St James the Apostle', '13-1-10');
INSERT INTO location VALUES (140, 'Kingsbridge', 26, 'St Edmund King and Martyr', '11-2-25');
INSERT INTO location VALUES (141, 'Kingskerswell', 12, 'St Mary', '7-3-0');
INSERT INTO location VALUES (142, 'Kingsteignton', 12, 'St Michael', '16-3-11');
INSERT INTO location VALUES (143, 'Kingston', 26, 'St James', '10-0-26');
INSERT INTO location VALUES (144, 'Lamerton', 21, 'St Peter', '11-1-26');
INSERT INTO location VALUES (145, 'Landkey', 19, 'St Paul', '13cwt');
INSERT INTO location VALUES (146, 'Langtree', 24, 'All Saints', '11cwt');
INSERT INTO location VALUES (147, 'Lapford', 3, 'St Thomas of Canterbury', '12cwt');
INSERT INTO location VALUES (148, 'Lifton', 21, 'St Mary', '21-0-16');
INSERT INTO location VALUES (149, 'Little Torrington', 24, 'St Giles', '12cwt');
INSERT INTO location VALUES (150, 'Littleham', 6, 'St Swithin', '8-1-17');
INSERT INTO location VALUES (151, 'Loddiswell', 26, 'St Michael and All Angels', '9-1-18');
INSERT INTO location VALUES (152, 'Longborough', 17, 'St James', '11-0-2');
INSERT INTO location VALUES (153, 'Loxhore', 19, 'St Michael and All Angels', '5cwt');
INSERT INTO location VALUES (154, 'Luppit', 8, 'St Mary', '10-3-21');
INSERT INTO location VALUES (155, 'Lustleigh', 11, 'St John the Baptist', '12-0-0');
INSERT INTO location VALUES (156, 'Lydford', 21, 'St Petrock', '8cwt');
INSERT INTO location VALUES (157, 'Lympstone', 1, 'Nativity of Blessed Virgin Mar', '9-2-2');
INSERT INTO location VALUES (158, 'Lynton', 19, 'St Mary the Virgin', '9-3-2');
INSERT INTO location VALUES (159, 'Maker', 17, 'St Mary and St Julian', '13-0-17');
INSERT INTO location VALUES (160, 'Malborough', 26, 'All Saints', '9-2-7');
INSERT INTO location VALUES (161, 'Manaton', 11, 'St Winifred', '8-0-14');
INSERT INTO location VALUES (162, 'Mariansleigh', 20, 'St Mary', '7-2-13');
INSERT INTO location VALUES (163, 'Marldon', 25, 'St John the Baptist', '15-3-0');
INSERT INTO location VALUES (164, 'Marwood', 2, 'St Michael and All Angels', '13-2-13');
INSERT INTO location VALUES (165, 'Meavy', 21, 'St Peter', '7-2-21');
INSERT INTO location VALUES (166, 'Merton', 24, 'All Saints', '10cwt');
INSERT INTO location VALUES (167, 'Milton Abbot', 21, 'St Constantine', '13cwt');
INSERT INTO location VALUES (168, 'Modbury', 26, 'St George', '17-2-7');
INSERT INTO location VALUES (169, 'Molland', 20, 'St Mary', '14-1-24');
INSERT INTO location VALUES (170, 'Monkleigh', 6, 'St George', '8-2-15');
INSERT INTO location VALUES (171, 'Morchard Bishop', 3, 'St Mary', '15cwt');
INSERT INTO location VALUES (172, 'Morebath', 22, 'St George', '8-3-5');
INSERT INTO location VALUES (173, 'Moretonhampstead', 11, 'St Andrew', '15-0-7');
INSERT INTO location VALUES (174, 'Mortehoe', 2, 'St Mary Magdalene', '9-0-26');
INSERT INTO location VALUES (175, 'Morwenstow', 17, 'St John the Baptist', '8cwt');
INSERT INTO location VALUES (176, 'Newton Abbot, Wolborough', 12, 'St Mary', '15-3-27');
INSERT INTO location VALUES (177, 'Newton Ferrers', 9, 'Holy Cross', '10-3-15');
INSERT INTO location VALUES (178, 'Newton St Cyres', 3, 'St Cyr and St Julitta', '12-3-22');
INSERT INTO location VALUES (179, 'North Bovey', 11, 'St John the Baptist', '12cwt');
INSERT INTO location VALUES (180, 'North Tawton', 15, 'St Peter', '18cwt');
INSERT INTO location VALUES (181, 'Northam', 6, 'St Margaret', '13-2-25');
INSERT INTO location VALUES (182, 'Northlew', 15, 'St Thomas of Canterbury', '6-3-5');
INSERT INTO location VALUES (183, 'Not Applicable', 14, 'Not Applicable', 'NA');
INSERT INTO location VALUES (184, 'Not Held', 14, 'Not Applicable', 'NA');
INSERT INTO location VALUES (185, 'Offwell', 8, 'St Mary the Virgin', '7-3-9');
INSERT INTO location VALUES (186, 'Okehampton', 15, 'All Saints', '16-2-13');
INSERT INTO location VALUES (187, 'Otterton', 1, 'St Michael', '12-0-4');
INSERT INTO location VALUES (188, 'Paignton', 23, 'St John the Baptist', '21-3-5');
INSERT INTO location VALUES (189, 'Parkham', 6, 'St James', '7-3-22');
INSERT INTO location VALUES (190, 'Petersmarland', 24, 'St Peter', '7.5cwt');
INSERT INTO location VALUES (191, 'Petrockstowe', 24, 'St Petrock', '8-0-14');
INSERT INTO location VALUES (192, 'Pilton', 2, 'St Mary the Virgin', '23-2-5');
INSERT INTO location VALUES (193, 'Plymouth, Eggbuckland', 18, 'St Edward', '10-0-0');
INSERT INTO location VALUES (194, 'Plymouth, Emmanuel', 18, 'Emmanuel', '19-3-14');
INSERT INTO location VALUES (195, 'Plymouth, Laira', 18, 'St Mary the Virgin', '11-0-14');
INSERT INTO location VALUES (196, 'Plymouth, Plymstock', 18, 'St Mary and All Saints', '13-1-10');
INSERT INTO location VALUES (197, 'Plymouth, St Budeaux', 18, 'St Budeaux', '12-0-25');
INSERT INTO location VALUES (198, 'Plymouth, Stoke Damerel', 18, 'St Andrew', '4-2-12');
INSERT INTO location VALUES (199, 'Plympton, St Mary', 18, 'The Blessed Virgin Mary', '25-1-11');
INSERT INTO location VALUES (200, 'Plympton, St Maurice', 18, 'St Maurice', '16-0-2');
INSERT INTO location VALUES (201, 'Plymtree', 16, 'St John the Baptist', '11-0-8');
INSERT INTO location VALUES (202, 'Poughill (Cornwall)', 17, 'St Olaf King and Martyr', '12-3-26');
INSERT INTO location VALUES (203, 'Poughill (Devon)', 3, 'St Michael and All Angels', '11-0-15');
INSERT INTO location VALUES (204, 'Powderham', 10, 'St Clement', '10cwt');
INSERT INTO location VALUES (205, 'Pyworthy', 7, 'St Swithun', '8-1-20');
INSERT INTO location VALUES (206, 'Rackenford', 22, 'All Saints', '14-2-8');
INSERT INTO location VALUES (207, 'Revelstoke', 9, 'St Peter', '16cwt');
INSERT INTO location VALUES (208, 'Rewe', 3, 'St Mary the Virgin', '9-1-0');
INSERT INTO location VALUES (209, 'Roborough', 24, 'St Peter', '12-1-18');
INSERT INTO location VALUES (210, 'Rose Ash', 20, 'St Peter', '9cwt');
INSERT INTO location VALUES (211, 'Salcombe', 26, 'Holy Trinity', '8-1-10');
INSERT INTO location VALUES (212, 'Sampford Courtenay', 15, 'St Andrew', '13-3-2');
INSERT INTO location VALUES (213, 'Sandford', 3, 'St Swithin', '10-2-22');
INSERT INTO location VALUES (214, 'Shaugh Prior', 9, 'St Edward', '15-1-3');
INSERT INTO location VALUES (215, 'Shebbear', 9, 'St Michael', '9-2-6');
INSERT INTO location VALUES (216, 'Sheepstor', 21, 'St Leonard', '6-2-19');
INSERT INTO location VALUES (217, 'Sherford', 26, 'St Martin', '12-1-19');
INSERT INTO location VALUES (218, 'Shirwell', 19, 'St Peter', '11-2-20');
INSERT INTO location VALUES (219, 'Shobrooke', 3, 'St Swithin', '12-2-10');
INSERT INTO location VALUES (220, 'Sidbury', 16, 'SS Peter and Giles', '16-1-23');
INSERT INTO location VALUES (221, 'Slapton', 26, 'St James the Greater', '5-1-12');
INSERT INTO location VALUES (222, 'South Brent', 25, 'St Petroc', '13-2-12');
INSERT INTO location VALUES (223, 'South Milton', 26, 'All Saints', '12cwt');
INSERT INTO location VALUES (224, 'South Molton', 20, 'St Mary Magdalene', '24-2-12');
INSERT INTO location VALUES (225, 'South Petherwin', 17, 'St Paternus', '12-2-25');
INSERT INTO location VALUES (226, 'South Pool', 26, 'St Cyriac', '11-0-4');
INSERT INTO location VALUES (227, 'South Tawton', 15, 'St Andrew', '11-3-2');
INSERT INTO location VALUES (228, 'Spreyton', 15, 'St Michael', '12cwt');
INSERT INTO location VALUES (229, 'St Giles in the Wood', 24, 'St Giles', '10-0-25');
INSERT INTO location VALUES (230, 'St Olave, City of London', 17, 'St Olave', '11-3-23');
INSERT INTO location VALUES (231, 'St Vedast, City of London', 17, 'St Vedast', '16-2-12');
INSERT INTO location VALUES (232, 'Staverton', 25, 'St Paul de Leon', '19-2-14');
INSERT INTO location VALUES (233, 'Stoke Fleming', 26, 'St Peter', '12-2-17');
INSERT INTO location VALUES (234, 'Stoke Gabriel', 25, 'St Gabriel', '17cwt');
INSERT INTO location VALUES (235, 'Stokeinteignhead', 12, 'St Andrew', '10-0-3');
INSERT INTO location VALUES (236, 'Stokenham', 26, 'St Michael and All Angels', '15-2-6');
INSERT INTO location VALUES (237, 'Stoodleigh', 22, 'St Margaret', '7-0-3');
INSERT INTO location VALUES (238, 'Stratton', 17, 'St Andrew', '21-3-16');
INSERT INTO location VALUES (239, 'Swimbridge', 19, 'St James the Apostle', '11-3-3');
INSERT INTO location VALUES (240, 'Talaton', 16, 'St James Apostle and Martyr', '12-2-22');
INSERT INTO location VALUES (241, 'Tavistock', 21, 'St Eustachius', '24-0-5');
INSERT INTO location VALUES (242, 'Tawstock', 24, 'St Peter', '16-3-20');
INSERT INTO location VALUES (243, 'Tedburn St Mary', 10, 'St Mary the Virgin', '10-0-6');
INSERT INTO location VALUES (244, 'Thorverton', 3, 'St Thomas of Canterbury', '15-0-4');
INSERT INTO location VALUES (245, 'Throwleigh', 15, 'St Mary the Virgin', '8-1-24');
INSERT INTO location VALUES (246, 'Thurlestone', 26, 'All Saints', '13-0-3');
INSERT INTO location VALUES (247, 'Tiverton, St Paul', 22, 'St Paul', '8-3-5');
INSERT INTO location VALUES (248, 'Torquay, Babbacombe', 23, 'All Saints', '13-0-26');
INSERT INTO location VALUES (249, 'Torquay, Cockington', 23, 'SS Geogre and Mary', '8-3-5');
INSERT INTO location VALUES (250, 'Torquay, St Marychurch', 23, 'St Mary the Virgin', '17-1-24');
INSERT INTO location VALUES (251, 'Torquay, Upton', 23, 'St Mary Magdalene', '14-2-12');
INSERT INTO location VALUES (252, 'Trusham', 11, 'St Michael and All Angels', '7cwt');
INSERT INTO location VALUES (253, 'Ugborough', 9, 'St Peter', '19cwt');
INSERT INTO location VALUES (254, 'Unknown', 14, 'Not Applicable', 'NA');
INSERT INTO location VALUES (255, 'Upton Pyne', 3, 'Our Lady', '8.5cwt');
INSERT INTO location VALUES (256, 'Walkhampton', 21, 'St Mary the Virgin', '7-3-12');
INSERT INTO location VALUES (257, 'Warkleigh', 20, 'St John the Evangelist', '9-1-11');
INSERT INTO location VALUES (258, 'Washford Pyne', 3, 'St Peter', '7cwt');
INSERT INTO location VALUES (259, 'Weare Giffard', 6, 'Holy Trinity', '7-1-26');
INSERT INTO location VALUES (260, 'Week St Mary', 17, 'St Mary the Virgin', '8-2-24');
INSERT INTO location VALUES (261, 'Welcombe', 6, 'St Nectan', '7-0-17');
INSERT INTO location VALUES (262, 'Wembury', 9, 'St Werburgh', '6-1-11');
INSERT INTO location VALUES (263, 'West Alvington', 26, 'All Saints', '16cwt');
INSERT INTO location VALUES (264, 'West Buckland', 19, 'St Peter', '7-0-22');
INSERT INTO location VALUES (265, 'West Down', 2, 'St Calixtus', '8-2-3');
INSERT INTO location VALUES (266, 'West Teignmouth (St James)', 10, 'St James the Less', '12-2-17');
INSERT INTO location VALUES (267, 'West Worlington', 20, 'St Mary', '7-3-21');
INSERT INTO location VALUES (268, 'Westleigh', 6, 'St Peter', '11-0-17');
INSERT INTO location VALUES (269, 'Whimple', 16, 'St Mary', '12-2-15');
INSERT INTO location VALUES (270, 'Whitchurch', 21, 'St Andrew', '11-1-8');
INSERT INTO location VALUES (271, 'Whitestone', 10, 'St Catherine', '11.5cwt');
INSERT INTO location VALUES (272, 'Widecombe in the Moor', 11, 'St Pancras', '12-3-14');
INSERT INTO location VALUES (273, 'Winford', 17, 'Blessed Virgin Mery and St Peter', '13-3-26');
INSERT INTO location VALUES (274, 'Winkleigh', 24, 'All Saints', '19-0-27');
INSERT INTO location VALUES (275, 'Witheridge', 20, 'St John the Baptist', '23-3-6');
INSERT INTO location VALUES (276, 'Woolfardisworthy (West) [Woolsery]', 6, 'Holy Trinity', '7-2-16');
INSERT INTO location VALUES (277, 'Yarnscombe', 24, 'St Andrew', '13cwt');
INSERT INTO location VALUES (278, 'Yealmpton', 9, 'St Bartholomew', '10-2-9');
INSERT INTO location VALUES (279, 'Zeal Monachorum', 3, 'St Peter', '8-0-26');

-- teams
INSERT INTO team VALUES (1, 'Abbotsham', 6);
INSERT INTO team VALUES (2, 'Alwington', 6);
INSERT INTO team VALUES (3, 'Alwington B', 6);
INSERT INTO team VALUES (4, 'Appledore', 6);
INSERT INTO team VALUES (5, 'Appledore B', 6);
INSERT INTO team VALUES (6, 'Appledore Ladies', 6);
INSERT INTO team VALUES (7, 'Arlington', 19);
INSERT INTO team VALUES (8, 'Arthur Froods VI', 13);
INSERT INTO team VALUES (9, 'Ashburton', 11);
INSERT INTO team VALUES (10, 'Ashreigney', 24);
INSERT INTO team VALUES (11, 'Atherington', 24);
INSERT INTO team VALUES (12, 'Awlington B', 6);
INSERT INTO team VALUES (13, 'Barnstaple', 2);
INSERT INTO team VALUES (14, 'Barnstaple B', 2);
INSERT INTO team VALUES (15, 'Bath & Wells Diocese Association - Axbridge Branch', 17);
INSERT INTO team VALUES (16, 'Bath & Wells Diocese Association - Glaston Branch', 17);
INSERT INTO team VALUES (17, 'Beaford', 7);
INSERT INTO team VALUES (18, 'Belstone', 15);
INSERT INTO team VALUES (19, 'Bere Ferrers', 21);
INSERT INTO team VALUES (20, 'Bere Ferrers B', 21);
INSERT INTO team VALUES (21, 'Berry Pomeroy', 25);
INSERT INTO team VALUES (22, 'Berrynarbor', 19);
INSERT INTO team VALUES (23, 'Berrynarbor B', 19);
INSERT INTO team VALUES (24, 'Bickington', 11);
INSERT INTO team VALUES (25, 'Bickington B', 11);
INSERT INTO team VALUES (26, 'Bickleigh (nr Plymouth)', 9);
INSERT INTO team VALUES (27, 'Bickleigh (nr Plymouth) B', 9);
INSERT INTO team VALUES (28, 'Bideford', 6);
INSERT INTO team VALUES (29, 'Bideford B', 6);
INSERT INTO team VALUES (30, 'Bigbury', 26);
INSERT INTO team VALUES (31, 'Birmingham', 17);
INSERT INTO team VALUES (32, 'Bishops Nympton', 20);
INSERT INTO team VALUES (33, 'Bishops Tawton', 2);
INSERT INTO team VALUES (34, 'Bishops Tawton B', 2);
INSERT INTO team VALUES (35, 'Bishopsteignton', 10);
INSERT INTO team VALUES (36, 'Black Torrington', 7);
INSERT INTO team VALUES (37, 'Blackawton', 26);
INSERT INTO team VALUES (38, 'Bondleigh', 15);
INSERT INTO team VALUES (39, 'Botus Fleming', 17);
INSERT INTO team VALUES (40, 'Botus Fleming B', 17);
INSERT INTO team VALUES (41, 'Bovey Tracey', 11);
INSERT INTO team VALUES (42, 'Bovey Tracey B', 11);
INSERT INTO team VALUES (43, 'Bow', 3);
INSERT INTO team VALUES (44, 'Bow B', 3);
INSERT INTO team VALUES (45, 'Bradford', 7);
INSERT INTO team VALUES (46, 'Bradford B', 7);
INSERT INTO team VALUES (47, 'Bradworthy', 7);
INSERT INTO team VALUES (48, 'Bratton Clovelly', 15);
INSERT INTO team VALUES (49, 'Bratton Fleming', 19);
INSERT INTO team VALUES (50, 'Braunton', 2);
INSERT INTO team VALUES (51, 'Braunton B', 2);
INSERT INTO team VALUES (52, 'Braunton Old Boys', 13);
INSERT INTO team VALUES (53, 'Brents All Stars', 13);
INSERT INTO team VALUES (54, 'Bridestowe', 15);
INSERT INTO team VALUES (55, 'Bridestowe B', 15);
INSERT INTO team VALUES (56, 'Bridford', 10);
INSERT INTO team VALUES (57, 'Bridgerule', 7);
INSERT INTO team VALUES (58, 'Bridgerule B', 7);
INSERT INTO team VALUES (59, 'Bristol', 17);
INSERT INTO team VALUES (60, 'Brixham', 23);
INSERT INTO team VALUES (61, 'Brixton', 9);
INSERT INTO team VALUES (62, 'Brixton B', 9);
INSERT INTO team VALUES (63, 'Broadhempston', 25);
INSERT INTO team VALUES (64, 'Broadhempston B', 25);
INSERT INTO team VALUES (65, 'Broadhempston C', 25);
INSERT INTO team VALUES (66, 'Broadwood Kelly', 24);
INSERT INTO team VALUES (67, 'Broadwoodkelly', 24);
INSERT INTO team VALUES (68, 'Buckfastleigh', 25);
INSERT INTO team VALUES (69, 'Buckland Brewer', 6);
INSERT INTO team VALUES (70, 'Buckland Filleigh', 24);
INSERT INTO team VALUES (71, 'Buckland in the Moor', 11);
INSERT INTO team VALUES (72, 'Buckland in the Moor B', 11);
INSERT INTO team VALUES (73, 'Buckland Monachorum', 21);
INSERT INTO team VALUES (74, 'Buckland Monachorum B', 21);
INSERT INTO team VALUES (75, 'Burrington', 20);
INSERT INTO team VALUES (76, 'Burrington B', 20);
INSERT INTO team VALUES (77, 'Cadbury', 3);
INSERT INTO team VALUES (78, 'Callington', 17);
INSERT INTO team VALUES (79, 'Chagford', 15);
INSERT INTO team VALUES (80, 'Chagford B', 15);
INSERT INTO team VALUES (81, 'Chagford C', 15);
INSERT INTO team VALUES (82, 'Chawleigh', 20);
INSERT INTO team VALUES (83, 'Cheriton Fitzpaine', 3);
INSERT INTO team VALUES (84, 'Chittlehampton', 20);
INSERT INTO team VALUES (85, 'Chivelstone', 26);
INSERT INTO team VALUES (86, 'Christow', 10);
INSERT INTO team VALUES (87, 'Christow B', 10);
INSERT INTO team VALUES (88, 'Chudleigh', 11);
INSERT INTO team VALUES (89, 'Chudleigh B', 11);
INSERT INTO team VALUES (90, 'Churchstow', 26);
INSERT INTO team VALUES (91, 'Clawton', 7);
INSERT INTO team VALUES (92, 'Clawton B', 7);
INSERT INTO team VALUES (93, 'Clovelly', 6);
INSERT INTO team VALUES (94, 'Clovelly B', 6);
INSERT INTO team VALUES (95, 'Clovelly C', 6);
INSERT INTO team VALUES (96, 'Clyst Hydon', 5);
INSERT INTO team VALUES (97, 'Clyst Hydon B', 5);
INSERT INTO team VALUES (98, 'Coffinswell', 12);
INSERT INTO team VALUES (99, 'Colaton Raleigh', 16);
INSERT INTO team VALUES (100, 'Coldridge', 3);
INSERT INTO team VALUES (101, 'Colebrooke', 3);
INSERT INTO team VALUES (102, 'Colebrooke B', 3);
INSERT INTO team VALUES (103, 'Collaton St Mary', 25);
INSERT INTO team VALUES (104, 'Collaton St Mary B', 25);
INSERT INTO team VALUES (105, 'Combe Martin', 19);
INSERT INTO team VALUES (106, 'Combe Martin B', 19);
INSERT INTO team VALUES (107, 'Combeinteignhead', 12);
INSERT INTO team VALUES (108, 'Cornwood', 9);
INSERT INTO team VALUES (109, 'Cornwood B', 9);
INSERT INTO team VALUES (110, 'Cornworthy', 25);
INSERT INTO team VALUES (111, 'Cullompton', 5);
INSERT INTO team VALUES (112, 'Dartington', 25);
INSERT INTO team VALUES (113, 'Dartington B', 25);
INSERT INTO team VALUES (114, 'Dartmouth Captains Team', 13);
INSERT INTO team VALUES (115, 'Dartmouth Ladies', 25);
INSERT INTO team VALUES (116, 'Dartmouth, St Petrox', 25);
INSERT INTO team VALUES (117, 'Dartmouth, St Saviour', 25);
INSERT INTO team VALUES (118, 'Dartmouth, St Saviour B', 25);
INSERT INTO team VALUES (119, 'Dartmouth, Townstal', 25);
INSERT INTO team VALUES (120, 'Dawlish', 10);
INSERT INTO team VALUES (121, 'Dawlish B', 10);
INSERT INTO team VALUES (122, 'Dean Prior', 25);
INSERT INTO team VALUES (123, 'Dean Prior B', 25);
INSERT INTO team VALUES (124, 'Devon Belles', 13);
INSERT INTO team VALUES (125, 'Devon Ringers Council', 13);
INSERT INTO team VALUES (126, 'Devon Youth', 13);
INSERT INTO team VALUES (127, 'Ding Dong Belles', 13);
INSERT INTO team VALUES (128, 'Diptford', 25);
INSERT INTO team VALUES (129, 'Diptford B', 25);
INSERT INTO team VALUES (130, 'Dittisham', 25);
INSERT INTO team VALUES (131, 'Dodbrooke', 26);
INSERT INTO team VALUES (132, 'Doddiscombsleigh', 10);
INSERT INTO team VALUES (133, 'Dolton', 24);
INSERT INTO team VALUES (134, 'Dolton B', 24);
INSERT INTO team VALUES (135, 'Dorset', 17);
INSERT INTO team VALUES (136, 'Dowland', 24);
INSERT INTO team VALUES (137, 'Down St Mary', 3);
INSERT INTO team VALUES (138, 'Down St Mary B', 3);
INSERT INTO team VALUES (139, 'Drewsteignton', 15);
INSERT INTO team VALUES (140, 'Drewsteignton B', 15);
INSERT INTO team VALUES (141, 'Dunsford', 10);
INSERT INTO team VALUES (142, 'Dunsford B', 10);
INSERT INTO team VALUES (143, 'Dunsford C', 10);
INSERT INTO team VALUES (144, 'Durham', 17);
INSERT INTO team VALUES (145, 'Durham B', 17);
INSERT INTO team VALUES (146, 'East Allington', 26);
INSERT INTO team VALUES (147, 'East Anstey', 20);
INSERT INTO team VALUES (148, 'East Anstey B', 20);
INSERT INTO team VALUES (149, 'East Buckland', 20);
INSERT INTO team VALUES (150, 'East Portlemouth', 26);
INSERT INTO team VALUES (151, 'Egloshayle', 17);
INSERT INTO team VALUES (152, 'Ermington', 9);
INSERT INTO team VALUES (153, 'Exbourne', 15);
INSERT INTO team VALUES (154, 'Exeter Branch', 13);
INSERT INTO team VALUES (155, 'Exeter Cathedral', 4);
INSERT INTO team VALUES (156, 'Exeter Colleges Guild', 4);
INSERT INTO team VALUES (157, 'Exeter, Alphington', 4);
INSERT INTO team VALUES (158, 'Exeter, Alphington B', 4);
INSERT INTO team VALUES (159, 'Exeter, Alphington C', 4);
INSERT INTO team VALUES (160, 'Exeter, Exwick', 4);
INSERT INTO team VALUES (161, 'Exeter, Pinhoe', 1);
INSERT INTO team VALUES (162, 'Exeter, St David', 4);
INSERT INTO team VALUES (163, 'Exeter, St David B', 4);
INSERT INTO team VALUES (164, 'Exeter, St Mark', 4);
INSERT INTO team VALUES (165, 'Exeter, St Petrock', 4);
INSERT INTO team VALUES (166, 'Exeter, St Petrock B', 4);
INSERT INTO team VALUES (167, 'Exeter, St Petrock Ladies', 4);
INSERT INTO team VALUES (168, 'Exeter, St Thomas', 4);
INSERT INTO team VALUES (169, 'Exminster', 10);
INSERT INTO team VALUES (170, 'Exminster B', 10);
INSERT INTO team VALUES (171, 'Exminster C', 10);
INSERT INTO team VALUES (172, 'Exmouth, Withycombe Raleigh', 1);
INSERT INTO team VALUES (173, 'Filleigh', 20);
INSERT INTO team VALUES (174, 'Four Shires Guild', 17);
INSERT INTO team VALUES (175, 'Frithelstock', 24);
INSERT INTO team VALUES (176, 'Frithelstock B', 24);
INSERT INTO team VALUES (177, 'Frithelstock C', 24);
INSERT INTO team VALUES (178, 'Galmpton', 26);
INSERT INTO team VALUES (179, 'Georgeham', 2);
INSERT INTO team VALUES (180, 'Georgeham B', 2);
INSERT INTO team VALUES (181, 'Gidleigh', 15);
INSERT INTO team VALUES (182, 'Goodleigh', 2);
INSERT INTO team VALUES (183, 'Great Torrington', 24);
INSERT INTO team VALUES (184, 'Halberton', 5);
INSERT INTO team VALUES (185, 'Halwell', 25);
INSERT INTO team VALUES (186, 'Halwell B', 25);
INSERT INTO team VALUES (187, 'Hampshire', 17);
INSERT INTO team VALUES (188, 'Hampshire West', 17);
INSERT INTO team VALUES (189, 'Harberton', 25);
INSERT INTO team VALUES (190, 'Hartland', 6);
INSERT INTO team VALUES (191, 'Hartland Ladies', 6);
INSERT INTO team VALUES (192, 'Hatherleigh', 15);
INSERT INTO team VALUES (193, 'Heanton Punchardon', 2);
INSERT INTO team VALUES (194, 'High Bickington', 24);
INSERT INTO team VALUES (195, 'High Bickington B', 24);
INSERT INTO team VALUES (196, 'High Bray', 20);
INSERT INTO team VALUES (197, 'Highweek', 12);
INSERT INTO team VALUES (198, 'Highweek B', 12);
INSERT INTO team VALUES (199, 'Hill Billys', 13);
INSERT INTO team VALUES (200, 'Holbeton', 9);
INSERT INTO team VALUES (201, 'Holbeton B', 9);
INSERT INTO team VALUES (202, 'Holcombe Burnell', 10);
INSERT INTO team VALUES (203, 'Holne', 11);
INSERT INTO team VALUES (204, 'Holne B', 25);
INSERT INTO team VALUES (205, 'Holsworthy', 7);
INSERT INTO team VALUES (206, 'Honeychurch', 15);
INSERT INTO team VALUES (207, 'Iddesleigh', 24);
INSERT INTO team VALUES (208, 'Iddesleigh B', 24);
INSERT INTO team VALUES (209, 'Iddesleigh Ladies', 24);
INSERT INTO team VALUES (210, 'Ide', 10);
INSERT INTO team VALUES (211, 'Ide B', 10);
INSERT INTO team VALUES (212, 'Ideford', 10);
INSERT INTO team VALUES (213, 'Ilfracombe, Holy Trinity', 2);
INSERT INTO team VALUES (214, 'Ilfracombe, Ss Philip and James', 2);
INSERT INTO team VALUES (215, 'Ilfracombe, Ss Philip and James B', 2);
INSERT INTO team VALUES (216, 'Ilsington', 11);
INSERT INTO team VALUES (217, 'Inwardleigh', 15);
INSERT INTO team VALUES (218, 'Ipplepen', 12);
INSERT INTO team VALUES (219, 'Ipplepen B', 12);
INSERT INTO team VALUES (220, 'Jacobstowe', 15);
INSERT INTO team VALUES (221, 'Kenn', 10);
INSERT INTO team VALUES (222, 'Kenn B', 10);
INSERT INTO team VALUES (223, 'Kenn Deanery', 10);
INSERT INTO team VALUES (224, 'Kenn/East Chinnock', 14);
INSERT INTO team VALUES (225, 'Kentisbeare', 5);
INSERT INTO team VALUES (226, 'Kentisbeare B', 5);
INSERT INTO team VALUES (227, 'Kentisbury', 19);
INSERT INTO team VALUES (228, 'Kenton', 10);
INSERT INTO team VALUES (229, 'Kenton B', 10);
INSERT INTO team VALUES (230, 'Kenton C', 10);
INSERT INTO team VALUES (231, 'Kilkhampton', 17);
INSERT INTO team VALUES (232, 'Kilkhampton B', 17);
INSERT INTO team VALUES (233, 'Kings Nympton', 20);
INSERT INTO team VALUES (234, 'Kingsbridge', 26);
INSERT INTO team VALUES (235, 'Kingskerswell', 12);
INSERT INTO team VALUES (236, 'Kingsteignton', 12);
INSERT INTO team VALUES (237, 'Kingsteignton B', 12);
INSERT INTO team VALUES (238, 'Kingsteignton Ladies', 12);
INSERT INTO team VALUES (239, 'Kingston', 26);
INSERT INTO team VALUES (240, 'Knowstone', 20);
INSERT INTO team VALUES (241, 'Ladies Team', 14);
INSERT INTO team VALUES (242, 'Lamerton', 21);
INSERT INTO team VALUES (243, 'Lamerton B', 21);
INSERT INTO team VALUES (244, 'Lamerton C', 21);
INSERT INTO team VALUES (245, 'Landkey', 2);
INSERT INTO team VALUES (246, 'Langtree', 24);
INSERT INTO team VALUES (247, 'Lanlivery', 17);
INSERT INTO team VALUES (248, 'Lansallos', 17);
INSERT INTO team VALUES (249, 'Lansallos B', 17);
INSERT INTO team VALUES (250, 'Lapford', 3);
INSERT INTO team VALUES (251, 'Launcells', 17);
INSERT INTO team VALUES (252, 'Launceston, St Mary', 17);
INSERT INTO team VALUES (253, 'Launceston, St Mary B', 17);
INSERT INTO team VALUES (254, 'Lewannick', 17);
INSERT INTO team VALUES (255, 'Liskeard', 17);
INSERT INTO team VALUES (256, 'Little Torrington', 24);
INSERT INTO team VALUES (257, 'Littleham', 6);
INSERT INTO team VALUES (258, 'Littleham B', 6);
INSERT INTO team VALUES (259, 'Littlehampton', 13);
INSERT INTO team VALUES (260, 'Loddiswell', 26);
INSERT INTO team VALUES (261, 'Longborough', 17);
INSERT INTO team VALUES (262, 'Lostwithiel', 17);
INSERT INTO team VALUES (263, 'Lostwithiel B', 17);
INSERT INTO team VALUES (264, 'Loxhore', 19);
INSERT INTO team VALUES (265, 'Lustleigh', 11);
INSERT INTO team VALUES (266, 'Lydford', 15);
INSERT INTO team VALUES (267, 'Lydford B', 15);
INSERT INTO team VALUES (268, 'Lynton', 19);
INSERT INTO team VALUES (269, 'Malborough', 26);
INSERT INTO team VALUES (270, 'Manaton', 11);
INSERT INTO team VALUES (271, 'Mariansleigh', 20);
INSERT INTO team VALUES (272, 'Mariansleigh B', 20);
INSERT INTO team VALUES (273, 'Marldon', 25);
INSERT INTO team VALUES (274, 'Marldon B', 25);
INSERT INTO team VALUES (275, 'Marwood', 2);
INSERT INTO team VALUES (276, 'Marystowe', 13);
INSERT INTO team VALUES (277, 'Meavy', 21);
INSERT INTO team VALUES (278, 'Meavy B', 21);
INSERT INTO team VALUES (279, 'Meavy/Walkhampton', 21);
INSERT INTO team VALUES (280, 'Meeth', 15);
INSERT INTO team VALUES (281, 'Merton', 24);
INSERT INTO team VALUES (282, 'Milton Abbot', 21);
INSERT INTO team VALUES (283, 'Modbury', 26);
INSERT INTO team VALUES (284, 'Modbury B', 26);
INSERT INTO team VALUES (285, 'Modbury C', 26);
INSERT INTO team VALUES (286, 'Molland', 20);
INSERT INTO team VALUES (287, 'Molland B', 20);
INSERT INTO team VALUES (288, 'Monkleigh', 6);
INSERT INTO team VALUES (289, 'Monkleigh B', 6);
INSERT INTO team VALUES (290, 'Monkleigh C', 6);
INSERT INTO team VALUES (291, 'Monkleigh Novice', 6);
INSERT INTO team VALUES (292, 'Moorland Ringers', 13);
INSERT INTO team VALUES (293, 'Morchard Bishop', 3);
INSERT INTO team VALUES (294, 'Morchard Bishop B', 3);
INSERT INTO team VALUES (295, 'Morebath', 22);
INSERT INTO team VALUES (296, 'Moreton Deanery', 11);
INSERT INTO team VALUES (297, 'Moreton Deanery B', 11);
INSERT INTO team VALUES (298, 'Moreton Deanery Youth Team', 11);
INSERT INTO team VALUES (299, 'Moretonhampstead', 11);
INSERT INTO team VALUES (300, 'Mortehoe', 2);
INSERT INTO team VALUES (301, 'Mortehoe B', 2);
INSERT INTO team VALUES (302, 'Morwenstow', 17);
INSERT INTO team VALUES (303, 'Neils Flyers', 13);
INSERT INTO team VALUES (304, 'Netherexe', 3);
INSERT INTO team VALUES (305, 'Newton Abbot, Wolborough', 12);
INSERT INTO team VALUES (306, 'Newton Abbot, Wolborough B', 12);
INSERT INTO team VALUES (307, 'Newton Ferrers', 9);
INSERT INTO team VALUES (308, 'Newton Ferrers B', 9);
INSERT INTO team VALUES (309, 'Newton Ferrers C', 9);
INSERT INTO team VALUES (310, 'Newton St Cyres', 3);
INSERT INTO team VALUES (311, 'North Bovey', 11);
INSERT INTO team VALUES (312, 'North Bovey B', 11);
INSERT INTO team VALUES (313, 'North Devon Belles', 13);
INSERT INTO team VALUES (314, 'North East Branch', 13);
INSERT INTO team VALUES (315, 'North Hill', 17);
INSERT INTO team VALUES (316, 'North Molton', 20);
INSERT INTO team VALUES (317, 'North Tawton', 15);
INSERT INTO team VALUES (318, 'North Tawton B', 15);
INSERT INTO team VALUES (319, 'Northam', 6);
INSERT INTO team VALUES (320, 'Northlew', 15);
INSERT INTO team VALUES (321, 'Okehampton', 15);
INSERT INTO team VALUES (322, 'Okehampton B', 15);
INSERT INTO team VALUES (323, 'Okehampton Deanery Young Ringers', 15);
INSERT INTO team VALUES (324, 'Otterton', 1);
INSERT INTO team VALUES (325, 'Otterton B', 3);
INSERT INTO team VALUES (326, 'Oxford Society', 17);
INSERT INTO team VALUES (327, 'Paignton', 23);
INSERT INTO team VALUES (328, 'Paignton B', 23);
INSERT INTO team VALUES (329, 'Parkham', 6);
INSERT INTO team VALUES (330, 'Petersmarland', 24);
INSERT INTO team VALUES (331, 'Petersmarland B', 24);
INSERT INTO team VALUES (332, 'Petrockstowe', 24);
INSERT INTO team VALUES (333, 'Pilton', 2);
INSERT INTO team VALUES (334, 'Pilton B', 2);
INSERT INTO team VALUES (335, 'Plymouth, Eggbuckland', 18);
INSERT INTO team VALUES (336, 'Plymouth, Eggbuckland B', 18);
INSERT INTO team VALUES (337, 'Plymouth, Emmanuel', 18);
INSERT INTO team VALUES (338, 'Plymouth, Emmanuel B', 18);
INSERT INTO team VALUES (339, 'Plymouth, Plymstock', 18);
INSERT INTO team VALUES (340, 'Plymouth, Plymstock B', 18);
INSERT INTO team VALUES (341, 'Plymouth, Plymstock C', 18);
INSERT INTO team VALUES (342, 'Plymouth, St Andrew', 18);
INSERT INTO team VALUES (343, 'Plymouth, St Budeaux', 18);
INSERT INTO team VALUES (344, 'Plymouth, Tamerton Foliot', 18);
INSERT INTO team VALUES (345, 'Plympton, St Mary', 18);
INSERT INTO team VALUES (346, 'Plympton, St Mary B', 18);
INSERT INTO team VALUES (347, 'Plympton, St Mary C', 18);
INSERT INTO team VALUES (348, 'Plympton, St Maurice', 18);
INSERT INTO team VALUES (349, 'Plympton, St Maurice B', 18);
INSERT INTO team VALUES (350, 'Plymtree', 16);
INSERT INTO team VALUES (351, 'Plymtree B', 16);
INSERT INTO team VALUES (352, 'Poughill (Cornwall)', 17);
INSERT INTO team VALUES (353, 'Poughill (Devon)', 3);
INSERT INTO team VALUES (354, 'Poundstock', 17);
INSERT INTO team VALUES (355, 'Powderham', 10);
INSERT INTO team VALUES (356, 'Pyworthy', 7);
INSERT INTO team VALUES (357, 'Rackenford', 22);
INSERT INTO team VALUES (358, 'Reed''s Team', 13);
INSERT INTO team VALUES (359, 'Revelstoke', 9);
INSERT INTO team VALUES (360, 'Rewe', 3);
INSERT INTO team VALUES (361, 'Rewe B', 3);
INSERT INTO team VALUES (362, 'Roborough', 24);
INSERT INTO team VALUES (363, 'Rose Ash', 20);
INSERT INTO team VALUES (364, 'Rose Ash B', 20);
INSERT INTO team VALUES (365, 'Salcombe', 26);
INSERT INTO team VALUES (366, 'Salcombe B', 26);
INSERT INTO team VALUES (367, 'Saltash', 17);
INSERT INTO team VALUES (368, 'Saltash, St Stephen', 17);
INSERT INTO team VALUES (369, 'Sampford Courtenay', 15);
INSERT INTO team VALUES (370, 'Sampford Courtenay & Ide', 13);
INSERT INTO team VALUES (371, 'Sampford Courtenay B', 15);
INSERT INTO team VALUES (372, 'Sampford Courtenay C', 15);
INSERT INTO team VALUES (373, 'Sandford', 3);
INSERT INTO team VALUES (374, 'Sandford B', 3);
INSERT INTO team VALUES (375, 'Scratch Team', 13);
INSERT INTO team VALUES (376, 'Shaugh Prior', 9);
INSERT INTO team VALUES (377, 'Shebbear', 24);
INSERT INTO team VALUES (378, 'Sheepstor', 21);
INSERT INTO team VALUES (379, 'Sheepwash', 24);
INSERT INTO team VALUES (380, 'Shepton Beauchamp', 17);
INSERT INTO team VALUES (381, 'Sherford', 26);
INSERT INTO team VALUES (382, 'Shirwell', 19);
INSERT INTO team VALUES (383, 'Slapton', 26);
INSERT INTO team VALUES (384, 'Society of Royal Cumberland Youths', 13);
INSERT INTO team VALUES (385, 'South Brent', 25);
INSERT INTO team VALUES (386, 'South Brent B', 25);
INSERT INTO team VALUES (387, 'South Brent C', 25);
INSERT INTO team VALUES (388, 'South Brent Ladies', 25);
INSERT INTO team VALUES (389, 'South Chew Stoke', 13);
INSERT INTO team VALUES (390, 'South Milton', 26);
INSERT INTO team VALUES (391, 'South Milton B', 26);
INSERT INTO team VALUES (392, 'South Molton', 20);
INSERT INTO team VALUES (393, 'South Petherton', 17);
INSERT INTO team VALUES (394, 'South Petherwin', 17);
INSERT INTO team VALUES (395, 'South Petherwin B', 17);
INSERT INTO team VALUES (396, 'South Petherwin C', 17);
INSERT INTO team VALUES (397, 'South Pool', 26);
INSERT INTO team VALUES (398, 'South Pool B', 26);
INSERT INTO team VALUES (399, 'South Tawton', 15);
INSERT INTO team VALUES (400, 'South Tawton B', 15);
INSERT INTO team VALUES (401, 'Spreyton', 15);
INSERT INTO team VALUES (402, 'Spreyton B', 15);
INSERT INTO team VALUES (403, 'Spreyton Ladies', 15);
INSERT INTO team VALUES (404, 'St Columb Major', 17);
INSERT INTO team VALUES (405, 'St Columb Major B', 17);
INSERT INTO team VALUES (406, 'St Germans', 17);
INSERT INTO team VALUES (407, 'St Giles in the Wood', 24);
INSERT INTO team VALUES (408, 'St Minver', 17);
INSERT INTO team VALUES (409, 'Staverton', 25);
INSERT INTO team VALUES (410, 'Stoke Canon', 3);
INSERT INTO team VALUES (411, 'Stoke Fleming', 26);
INSERT INTO team VALUES (412, 'Stoke Gabriel', 25);
INSERT INTO team VALUES (413, 'Stoke Gabriel B', 25);
INSERT INTO team VALUES (414, 'Stokeinteignhead', 12);
INSERT INTO team VALUES (415, 'Stokenham', 26);
INSERT INTO team VALUES (416, 'Stokenham B', 26);
INSERT INTO team VALUES (417, 'Straw Hats', 13);
INSERT INTO team VALUES (418, 'Swimbridge', 19);
INSERT INTO team VALUES (419, 'Swimbridge B', 19);
INSERT INTO team VALUES (420, 'Sydenham Damerel', 21);
INSERT INTO team VALUES (421, 'Talaton', 16);
INSERT INTO team VALUES (422, 'Talaton B', 16);
INSERT INTO team VALUES (423, 'Tamar Valley Belles', 13);
INSERT INTO team VALUES (424, 'Tavistock', 21);
INSERT INTO team VALUES (425, 'Tavistock B', 21);
INSERT INTO team VALUES (426, 'Tavistock Ladies', 21);
INSERT INTO team VALUES (427, 'Tawstock', 24);
INSERT INTO team VALUES (428, 'Tawstock B', 24);
INSERT INTO team VALUES (429, 'Tedburn St Mary', 10);
INSERT INTO team VALUES (430, 'Tedburn St Mary & South Tawton', 13);
INSERT INTO team VALUES (431, 'Tedburn St Mary B', 10);
INSERT INTO team VALUES (432, 'Teignmouth', 10);
INSERT INTO team VALUES (433, 'The Makers', 13);
INSERT INTO team VALUES (434, 'The Quarter Pealers', 13);
INSERT INTO team VALUES (435, 'Thelbridge', 20);
INSERT INTO team VALUES (436, 'Throwleigh', 15);
INSERT INTO team VALUES (437, 'Thrushelton', 21);
INSERT INTO team VALUES (438, 'Thurlestone', 26);
INSERT INTO team VALUES (439, 'Tiverton, St Paul', 22);
INSERT INTO team VALUES (440, 'Torquay, Babbacombe', 23);
INSERT INTO team VALUES (441, 'Torquay, St Marychurch', 23);
INSERT INTO team VALUES (442, 'Torquay, Upton', 23);
INSERT INTO team VALUES (443, 'Torquay, Upton B', 23);
INSERT INTO team VALUES (444, 'Torridge Valley', 13);
INSERT INTO team VALUES (445, 'Torrington Ladies', 24);
INSERT INTO team VALUES (446, 'Totnes', 25);
INSERT INTO team VALUES (447, 'Trusham', 11);
INSERT INTO team VALUES (448, 'Ugborough', 9);
INSERT INTO team VALUES (449, 'Ugborough B', 9);
INSERT INTO team VALUES (450, 'Upton Pyne', 3);
INSERT INTO team VALUES (451, 'Walkhampton', 21);
INSERT INTO team VALUES (452, 'Warkleigh', 20);
INSERT INTO team VALUES (453, 'Warwick', 17);
INSERT INTO team VALUES (454, 'Washford Pyne', 3);
INSERT INTO team VALUES (455, 'Weare Giffard', 6);
INSERT INTO team VALUES (456, 'Weare Giffard B', 6);
INSERT INTO team VALUES (457, 'Weare Giffard C', 6);
INSERT INTO team VALUES (458, 'Wednesday Night Ringers', 13);
INSERT INTO team VALUES (459, 'Wednesday Night Ringers B', 13);
INSERT INTO team VALUES (460, 'Week St Mary', 17);
INSERT INTO team VALUES (461, 'Welcombe', 6);
INSERT INTO team VALUES (462, 'Wembury', 9);
INSERT INTO team VALUES (463, 'Wembury B', 9);
INSERT INTO team VALUES (464, 'West Alvington', 26);
INSERT INTO team VALUES (465, 'West Alvington B', 26);
INSERT INTO team VALUES (466, 'West Buckland', 19);
INSERT INTO team VALUES (467, 'West Down', 2);
INSERT INTO team VALUES (468, 'West Down B', 2);
INSERT INTO team VALUES (469, 'Whimple', 16);
INSERT INTO team VALUES (470, 'Whitchurch', 21);
INSERT INTO team VALUES (471, 'Whitestone', 10);
INSERT INTO team VALUES (472, 'Widecombe in the Moor', 11);
INSERT INTO team VALUES (473, 'Widecombe in the Moor B', 11);
INSERT INTO team VALUES (474, 'Widecombe in the Moor C', 11);
INSERT INTO team VALUES (475, 'Widecombe in the Moor D', 11);
INSERT INTO team VALUES (476, 'Winford', 17);
INSERT INTO team VALUES (477, 'Winkleigh', 24);
INSERT INTO team VALUES (478, 'Winsford', 2);
INSERT INTO team VALUES (479, 'Witheridge', 20);
INSERT INTO team VALUES (480, 'Witheridge B', 20);
INSERT INTO team VALUES (481, 'Withiel', 17);
INSERT INTO team VALUES (482, 'Woodleigh Deanery Ladies Team', 26);
INSERT INTO team VALUES (483, 'Woolsery (aka West Woolfardiswothy)', 6);
INSERT INTO team VALUES (484, 'Worlington', 20);
INSERT INTO team VALUES (485, 'Worlington B', 20);
INSERT INTO team VALUES (486, 'Yarcombe', 8);
INSERT INTO team VALUES (487, 'Yarnscombe', 24);
INSERT INTO team VALUES (488, 'Yealmpton', 9);
INSERT INTO team VALUES (489, 'Yealmpton B', 9);
INSERT INTO team VALUES (490, 'Yealmpton C', 9);
INSERT INTO team VALUES (491, 'Zeal Monachorum', 3);
